-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.config
(
    lang character varying(255) COLLATE pg_catalog."default" NOT NULL,
    currency_id bigint NOT NULL
    );

CREATE TABLE IF NOT EXISTS public.currencies
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    rate_to_byn numeric(10, 5) NOT NULL,
    CONSTRAINT currencies_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.invoices
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    amount numeric(10, 2) NOT NULL,
    payment_system_id bigint,
    created_at integer NOT NULL,
    payed_at integer,
    user_id bigint NOT NULL,
    currency_id bigint,
    CONSTRAINT invoices_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.motorcycles
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    type_id bigint NOT NULL,
    created_at integer NOT NULL,
    vin character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT motorcycles_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.motorcycles_colors
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT motorcycles_colors_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.motorcycles_types
(
    id bigint NOT NULL,
    image character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    engine_volume integer NOT NULL,
    max_speed integer NOT NULL,
    fuel_rate numeric(10, 3) NOT NULL,
    color_id bigint NOT NULL,
    CONSTRAINT motorcycles_types_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.payments_systems
(
    id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT payments_systems_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.rentals
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    motorcycle_id bigint NOT NULL,
    created_at integer NOT NULL,
    duration_id bigint,
    expired_at integer NOT NULL,
    CONSTRAINT users_motorcycles_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.rentals_durations
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    days integer NOT NULL,
    cost integer NOT NULL,
    CONSTRAINT rental_durations_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.reservations_durations
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    rental_numbers integer NOT NULL,
    minutes integer NOT NULL,
    CONSTRAINT reservations_durations_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.reservations_motorcycles
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    motorcycle_id bigint NOT NULL,
    expired_at integer NOT NULL,
    duration_id bigint NOT NULL,
    CONSTRAINT motorcycles_reservations_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    phone_number character varying(32) COLLATE pg_catalog."default" NOT NULL,
    created_at integer NOT NULL,
    updated_at integer NOT NULL,
    balance numeric(10, 2),
    enter_code character varying(32) COLLATE pg_catalog."default" NOT NULL,
    enter_code_expired_at integer NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT phone_number UNIQUE (phone_number)
    );

ALTER TABLE IF EXISTS public.config
    ADD CONSTRAINT fk_c_currency_id_c_id FOREIGN KEY (currency_id)
    REFERENCES public.currencies (id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.invoices
    ADD CONSTRAINT fk_i_currency_id_c_id FOREIGN KEY (currency_id)
    REFERENCES public.currencies (id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.invoices
    ADD CONSTRAINT fk_i_payment_system_id_ps_id FOREIGN KEY (payment_system_id)
    REFERENCES public.payments_systems (id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.invoices
    ADD CONSTRAINT fk_i_user_id_u_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.motorcycles
    ADD CONSTRAINT fk_m_type_id_mt_id FOREIGN KEY (type_id)
    REFERENCES public.motorcycles_types (id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.motorcycles_types
    ADD CONSTRAINT fk_mt_color_id_mc_id FOREIGN KEY (color_id)
    REFERENCES public.motorcycles_colors (id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.rentals
    ADD CONSTRAINT fk_r_duration_id_rd_id FOREIGN KEY (duration_id)
    REFERENCES public.rentals_durations (id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.rentals
    ADD CONSTRAINT fk_r_motorcycle_id_m_id FOREIGN KEY (motorcycle_id)
    REFERENCES public.motorcycles (id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.rentals
    ADD CONSTRAINT fk_r_user_id_u_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.reservations_motorcycles
    ADD CONSTRAINT fk_rm_motorcycle_id_m_id FOREIGN KEY (motorcycle_id)
    REFERENCES public.motorcycles (id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.reservations_motorcycles
    ADD CONSTRAINT kf_rm_duration_id_rd_id FOREIGN KEY (duration_id)
    REFERENCES public.reservations_durations (id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE SET NULL
    NOT VALID;

END;